/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 table.glb 
*/

import React from 'react'
import { useGLTF, useTexture } from '@react-three/drei'
import { MeshBasicMaterial } from 'three'

export function Table({ surfaceTexture, legTexture }) {
  const { nodes, materials } = useGLTF('./3d-models/table/table.glb')

  const surfaceMaterial = new MeshBasicMaterial({ map: useTexture(surfaceTexture) })
  const legMaterial = new MeshBasicMaterial({ map: useTexture(legTexture) })

  return (
    <group dispose={null}>
      {/* surface */}
      <group position={[-4.702, 7.673, -1.24]} rotation={[0, 1.571, 0]}>
        <mesh geometry={nodes.Rectangle1758.geometry} material={surfaceMaterial} position={[0, -0.039, -1.713]} rotation={[-Math.PI, -1.571, 0]} scale={[-1, -1, -0.88]} />
        <mesh geometry={nodes.Rectangle1759.geometry} material={surfaceMaterial} position={[0, -0.039, 0.531]} rotation={[-Math.PI, -1.571, 0]} scale={[-1, -1, -0.88]} />
        <mesh geometry={nodes.Rectangle1760.geometry} material={surfaceMaterial} position={[0, -0.039, 0]} rotation={[-Math.PI, -1.571, 0]} scale={[-1, -1, -0.88]} />
      </group>
      <group position={[3.319, 7.673, -1.239]} rotation={[Math.PsurfaceMaterial, Math.PI / 2, 0]} scale={-1}>
        <mesh geometry={nodes.Rectangle1761.geometry} material={surfaceMaterial} position={[0, -0.039, 0.531]} rotation={[-Math.PI, -1.571, 0]} scale={[-1, -1, -0.88]} />
        <mesh geometry={nodes.Rectangle1762.geometry} material={surfaceMaterial} position={[0, -0.039, -1.713]} rotation={[-Math.PI, -1.571, 0]} scale={[-1, -1, -0.88]} />
        <mesh geometry={nodes.Rectangle1763.geometry} material={surfaceMaterial} position={[0, -0.039, 0]} rotation={[-Math.PI, -1.571, 0]} scale={[-1, -1, -0.88]} />
      </group>

      <mesh
        geometry={nodes.Line1808435.geometry}
        material={surfaceMaterial}
        position={[-27.603, 7.285, -7.977]}
        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        scale={-1}
      />
      <mesh
        geometry={nodes.Line1808436.geometry}
        material={surfaceMaterial}
        position={[27.603, 7.285, -7.977]}
        rotation={[Math.PI / 2, 0, 1.571]}
      />

      {/* leg 1 */}
      <mesh geometry={nodes.Line1808421.geometry} material={legMaterial} position={[-20.991, 0.094, 22.424]} rotation={[-Math.PI / 2, 0, -2.356]} scale={[-0.975, -1.489, -0.975]} />
      <mesh geometry={nodes.Line1808422.geometry} material={legMaterial} position={[-25.468, -21.309, 25.79]} rotation={[-Math.PI / 2, 0, 0]} scale={-1} />
      {/* leg 2 */}
      <mesh geometry={nodes.Line1808416.geometry} material={legMaterial} position={[-20.992, 0.094, -22.336]} rotation={[Math.PI / 2, 0, Math.PI / 4]} scale={[0.975, 1.489, 0.975]} />
      <mesh geometry={nodes.Line1808417.geometry} material={legMaterial} position={[-25.469, -21.309, -25.702]} rotation={[Math.PI / 2, 0, Math.PI]} />
      {/* leg 3 */}
      <mesh geometry={nodes.Line1808424.geometry} material={legMaterial} position={[25.704, -21.309, -25.702]} rotation={[Math.PI / 2, 0, Math.PI]} />
      <mesh geometry={nodes.Line1808425.geometry} material={legMaterial} position={[21.036, 0.094, -22.336]} rotation={[-Math.PI / 2, 0, Math.PI / 4]} scale={[-0.975, -1.489, -0.975]} />
      {/* leg 4 */}
      <mesh geometry={nodes.Line1808418.geometry} material={legMaterial} position={[21.038, 0.094, 22.423]} rotation={[Math.PI / 2, 0, -2.356]} scale={[0.975, 1.489, 0.975]} />
      <mesh geometry={nodes.Line1808419.geometry} material={legMaterial} position={[25.706, -21.309, 25.79]} rotation={[-Math.PI / 2, 0, 0]} scale={-1} />


      <group position={[-0.017, 6.038, -20.791]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
        <mesh geometry={nodes.Line1808426.geometry} material={materials["Material #25"]} position={[-1.405, -19.558, 0.526]} rotation={[0, 0, Math.PI]} scale={-1} />
        <mesh geometry={nodes.Line1808427.geometry} material={materials["Material #25"]} position={[-1.405, 18.245, 0.526]} rotation={[0, 0, Math.PI]} scale={-1} />
        <mesh geometry={nodes.Line1808428.geometry} material={materials["Material #25"]} position={[-1.405, 8.128, -0.526]} />
        <mesh geometry={nodes.Line1808429.geometry} material={materials["Material #25"]} position={[-1.405, 8.128, 0.526]} rotation={[0, 0, Math.PI]} scale={-1} />
        <mesh geometry={nodes.Line1808430.geometry} material={materials["Material #25"]} position={[-1.405, -9.483, -0.526]} />
        <mesh geometry={nodes.Line1808431.geometry} material={materials["Material #25"]} position={[-1.405, -19.558, -0.526]} />
        <mesh geometry={nodes.Line1808432.geometry} material={materials["Material #25"]} position={[-1.405, 18.245, -0.526]} />
        <mesh geometry={nodes.Line1808433.geometry} material={materials["Material #25"]} position={[-1.405, -9.483, 0.526]} rotation={[0, 0, Math.PI]} scale={-1} />
        <mesh geometry={nodes.Line1808434.geometry} material={materials["Material #25"]} position={[0.758, 0, -0.588]} rotation={[Math.PI / 2, 0, 0]} />
      </group>

      <mesh geometry={nodes.Line1808420.geometry} material={materials["Material #25"]} position={[-0.031, 4.501, -17.996]} rotation={[-Math.PI / 2, 0, 0]} scale={-1} />
      <mesh geometry={nodes.Line1808423.geometry} material={materials["Material #25"]} position={[-0.017, 6.627, 21.636]} rotation={[0, 1.571, 0]} scale={-1} />
      <mesh geometry={nodes.Line1808437.geometry} material={materials["Material #25"]} position={[18.228, 5.512, 19.679]} rotation={[-Math.PI / 2, 0, -1.571]} />
      <mesh geometry={nodes.Line1808438.geometry} material={materials["Material #25"]} position={[8.111, 6.564, 19.679]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={-1} />
      <mesh geometry={nodes.Line1808439.geometry} material={materials["Material #25"]} position={[8.111, 5.512, 19.679]} rotation={[-Math.PI / 2, 0, -1.571]} />
      <mesh geometry={nodes.Line1808440.geometry} material={materials["Material #25"]} position={[18.228, 6.564, 19.679]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={-1} />
      <mesh geometry={nodes.Line1808441.geometry} material={materials["Material #25"]} position={[-19.575, 5.512, 19.679]} rotation={[-Math.PI / 2, 0, -1.571]} />
      <mesh geometry={nodes.Line1808442.geometry} material={materials["Material #25"]} position={[-9.5, 6.564, 19.679]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={-1} />
      <mesh geometry={nodes.Line1808443.geometry} material={materials["Material #25"]} position={[-19.575, 6.564, 19.679]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={-1} />
      <mesh geometry={nodes.Line1808444.geometry} material={materials["Material #25"]} position={[-9.5, 5.512, 19.679]} rotation={[-Math.PI / 2, 0, -1.571]} />
      <mesh geometry={nodes.Rectangle1754.geometry} material={materials["Material #25"]} position={[8.738, 6.606, -11.511]} rotation={[0, 1.571, 0]} scale={-1} />
      <mesh geometry={nodes.Rectangle1755.geometry} material={materials["Material #25"]} position={[-8.875, 6.606, -11.511]} rotation={[0, 1.571, 0]} scale={-1} />
      <mesh geometry={nodes.Rectangle1756.geometry} material={materials["Material #25"]} position={[-18.908, 6.606, -11.511]} rotation={[0, 1.571, 0]} scale={-1} />
      <mesh geometry={nodes.Rectangle1757.geometry} material={materials["Material #25"]} position={[18.863, 6.606, -11.511]} rotation={[0, 1.571, 0]} scale={-1} />
    </group>
  )
}

useGLTF.preload('./3d-models/table/table.glb')
